-- ============================================================
-- NABA GOLD KARIGAR — Cloudflare D1 Schema
-- ============================================================
-- NOTE: This is for Cloudflare D1 (SQLite), NOT R2.
--       R2 = object storage (images only, no SQL).
--       D1 = the Cloudflare database that replaces Supabase PostgreSQL.
--
-- HOW TO USE:
--   Wrangler CLI:
--     npx wrangler d1 create naba-gold-db
--     npx wrangler d1 execute naba-gold-db --file=R2.sql
--
--   OR: Cloudflare Dashboard → D1 → your database → Console → paste → Run
--
-- KEY DIFFERENCES vs Supabase (PostgreSQL → SQLite):
--   • No UUID type         → TEXT
--   • No boolean type      → INTEGER (0 = false, 1 = true)
--   • No numeric/bigint    → REAL / INTEGER
--   • No text[] arrays     → TEXT (stored as JSON string e.g. '["url1","url2"]')
--   • No jsonb type        → TEXT (stored as JSON string)
--   • No RLS policies      → Access control must be done in your API/Workers layer
--   • No gen_random_uuid() → Application generates UUIDs before insert
-- ============================================================


-- ============================================================
-- SECTION 1: PRODUCTS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS products (
  id              TEXT    PRIMARY KEY,                      -- UUID generated by app
  title           TEXT    NOT NULL,
  description     TEXT    NOT NULL DEFAULT '',
  weightInGrams   REAL    NOT NULL,
  makingCharge    REAL    NOT NULL,
  chargeType      TEXT    NOT NULL DEFAULT 'flat'
                          CHECK (chargeType IN ('flat', 'percentage')),
  goldKarat       TEXT    NOT NULL DEFAULT '22K'
                          CHECK (goldKarat IN ('22K', '24K')),
  images          TEXT    NOT NULL DEFAULT '[]',            -- JSON array string
  popularityScore INTEGER NOT NULL DEFAULT 0,
  category        TEXT    NOT NULL DEFAULT '',
  subCategory     TEXT    NOT NULL DEFAULT '',
  isHidden        INTEGER NOT NULL DEFAULT 0,               -- 0=false, 1=true
  isOutofStock    INTEGER NOT NULL DEFAULT 0,
  showPrice       INTEGER NOT NULL DEFAULT 0,
  isExclusive     INTEGER NOT NULL DEFAULT 0,
  stockQuantity   INTEGER NOT NULL DEFAULT 0,
  createdAt       INTEGER NOT NULL,                         -- Unix ms timestamp
  updatedAt       INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_products_category    ON products (category);
CREATE INDEX IF NOT EXISTS idx_products_hidden      ON products (isHidden);
CREATE INDEX IF NOT EXISTS idx_products_oos         ON products (isOutofStock);
CREATE INDEX IF NOT EXISTS idx_products_exclusive   ON products (isExclusive);
CREATE INDEX IF NOT EXISTS idx_products_created     ON products (createdAt DESC);
CREATE INDEX IF NOT EXISTS idx_products_subcategory ON products (subCategory);


-- ============================================================
-- SECTION 2: REVIEWS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS reviews (
  id           TEXT    PRIMARY KEY,                         -- UUID generated by app
  customerName TEXT    NOT NULL,
  rating       INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment      TEXT    NOT NULL,
  isApproved   INTEGER NOT NULL DEFAULT 0,
  createdAt    INTEGER NOT NULL,
  updatedAt    INTEGER
);

CREATE INDEX IF NOT EXISTS idx_reviews_approved ON reviews (isApproved);
CREATE INDEX IF NOT EXISTS idx_reviews_created  ON reviews (createdAt DESC);


-- ============================================================
-- SECTION 3: SETTINGS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS settings (
  id          TEXT    PRIMARY KEY,
  rate22k     REAL    NOT NULL DEFAULT 0,
  rate24k     REAL    NOT NULL DEFAULT 0,
  logoUrl     TEXT    NOT NULL DEFAULT '',
  homeConfig  TEXT    NOT NULL DEFAULT '{}',               -- JSON string
  lastUpdated INTEGER NOT NULL DEFAULT 0
);

-- Seed default row
INSERT OR IGNORE INTO settings (id, rate22k, rate24k, logoUrl, homeConfig, lastUpdated)
VALUES (
  'goldRate',
  6800,
  7400,
  '',
  '{"heroSlides":[{"id":1,"image":"","heading":"Heritage Craft, Modern Precision.","subheading":"Bespoke gold jewelry direct from the Karigar.","ctaText":"Browse Catalog","ctaLink":"/catalog"}]}',
  strftime('%s', 'now') * 1000
);


-- ============================================================
-- SECTION 4: AUDIT LOGS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS audit_logs (
  id          TEXT    PRIMARY KEY,                          -- UUID generated by app
  admin_email TEXT    NOT NULL,
  action      TEXT    NOT NULL,
  details     TEXT    NOT NULL,
  created_at  INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_admin   ON audit_logs (admin_email);


-- ============================================================
-- SECTION 5: CATEGORIES TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS categories (
  id            TEXT    PRIMARY KEY,
  name          TEXT    NOT NULL,
  slug          TEXT    NOT NULL UNIQUE,
  image         TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at    INTEGER
);

CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories (slug);


-- ============================================================
-- SECTION 6: SUBCATEGORIES TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS subcategories (
  id            TEXT    PRIMARY KEY,
  category_id   TEXT    NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  name          TEXT    NOT NULL,
  slug          TEXT    NOT NULL,
  image         TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at    INTEGER
);

CREATE INDEX IF NOT EXISTS idx_subcategories_category_id ON subcategories (category_id);


-- ============================================================
-- DONE!
-- After running this:
--   ✓ All tables exist with correct columns
--   ✓ All indexes are in place
--   ✓ Default gold rate row is seeded
--
-- NEXT STEPS TO FULLY MIGRATE FROM SUPABASE:
--   1. Run this file against your D1 database (see HOW TO USE above)
--   2. Replace supabase-js client calls with a D1-compatible API
--      (e.g., Cloudflare Workers + Hono, or a REST adapter)
--   3. Migrate image storage: Supabase Storage → Cloudflare R2
--      (update upload logic in AdminCatalog.tsx + AdminPrivateCatalog.tsx)
--   4. Replace Supabase Auth with Cloudflare Access or another auth provider
--
-- IMPORTANT — What D1 does NOT have (vs Supabase):
--   • No Row Level Security (RLS) — protect routes via Cloudflare Workers
--   • No built-in Auth — use Cloudflare Access / Clerk / Auth.js
--   • No realtime subscriptions
--   • No storage bucket (use R2 separately for images)
-- ============================================================
